recommendation_engine:
  enabled: true
  model_version: 1.0
  update_interval_hours: 6

pricing_optimizer:
  enabled: true
  max_surge: 2.5
  min_surge: 1.0

analytics:
  enabled: true
  data_retention_days: 90
