name: Extract Project Code

on:
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Make script executable
      run: chmod +x extract_everything_all.sh

    - name: Run extraction script
      run: ./extract_everything_all.sh

    - name: Upload output file
      uses: actions/upload-artifact@v3
      with:
        name: all_project_code
        path: all_project_code.txt
